"""Make district columns nullable

Revision ID: 70ee405555b0
Revises: d520a13fe21a
Create Date: 2026-06-11 13:15:17.049614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70ee405555b0'
down_revision: Union[str, None] = 'd520a13fe21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cases', 'district',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('users', 'district',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'district',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('cases', 'district',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    # ### end Alembic commands ###
